services:
  mongodb:
    container_name: quiz-builder-mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  web:
    container_name: quiz-builder-web
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile
    ports:
      - "3000:8080"
    depends_on:
      - mongodb

volumes:
  mongodb_data_container:
